# do not touch the config version below, it will break the plugin!
configversion: 1.4
duelme:
    checkforupdates: true
    mysql:
       enabled: true
       host: 'localhost'
       port: '3306'
       database: 'duelmestats'
       user: 'root'
       pass: ''
    duel:
       countdowntime: 30
       dueltime: 120
       seperateinventories: true
       rightclicktoduel: false
       dropitemsondeath: false
       minbetamount: 500
    announce:
       duelstart: true
       deaths: true
       leavejoin: true
    commands:
       duelstart:
          - 'give %player% 298 1'
          - 'give %player% 299 1'
          - 'give %player% 300 1'
          - 'give %player% 301 1'
          - 'give %player% 268 1'
       duelwinner:
          - 'give %player% 267 1'
    debug:
       enabled: false